#!/usr/bin/env bash
# telem-init.sh — EmergenIT Linux Telemetry first-run setup
# Generates credentials, detects hostname, writes .env, optionally wires Claude Desktop

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$BASE_DIR/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${GREEN}[init]${NC} $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC} $*"; }
section() { echo -e "\n${CYAN}── $* ──${NC}"; }

section "EmergenIT Linux Telemetry — First Run Setup"

# ── Check dependencies ────────────────────────────────────────────────────
for dep in docker python3; do
    if ! command -v $dep &>/dev/null; then
        echo "ERROR: $dep is required but not installed."; exit 1
    fi
done
if ! docker compose version &>/dev/null; then
    echo "ERROR: docker compose plugin is required."; exit 1
fi

# ── Detect hostname ────────────────────────────────────────────────────────
DETECTED_HOST=$(hostname -s)
section "Hostname Detection"
echo "Detected: $DETECTED_HOST"
read -rp "Use this hostname? [Y/n]: " yn
if [[ "$yn" =~ ^[Nn] ]]; then
    read -rp "Enter hostname: " DETECTED_HOST
fi

# ── Generate or load credentials ───────────────────────────────────────────
section "Credentials"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists. Keeping existing credentials."
    warn "Delete $ENV_FILE and re-run to regenerate."
    # shellcheck source=/dev/null
    source "$ENV_FILE"
else
    info "Generating secure credentials..."

    INFLUX_PASSWORD=$(python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_letters+string.digits+'!@#%^&*') for _ in range(20)))")
    INFLUX_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    GRAFANA_PASSWORD=$(python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_letters+string.digits+'!@#%^&*') for _ in range(20)))")

    cat > "$ENV_FILE" << EOF
# EmergenIT Linux Telemetry — generated by telem init
# DO NOT commit this file to git

HOST_HOSTNAME=${DETECTED_HOST}

INFLUX_USER=admin
INFLUX_PASSWORD=${INFLUX_PASSWORD}
INFLUX_TOKEN=${INFLUX_TOKEN}

GRAFANA_USER=admin
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
EOF
    info ".env written with generated credentials."
    echo ""
    echo "  Grafana login:  admin / $GRAFANA_PASSWORD"
    echo "  Save these — they won't be shown again."
fi

# ── SSH hosts setup ────────────────────────────────────────────────────────
section "Remote Hosts (SSH)"
HOSTS_FILE="$BASE_DIR/hosts.yml"

if [[ -f "$HOSTS_FILE" ]]; then
    info "hosts.yml already exists — skipping."
else
    echo "Add remote hosts to audit via SSH."
    echo "Leave blank to skip (localhost is always audited)."
    echo ""

    HOSTS_ENTRIES="hosts:"$'\n'"  - name: ${DETECTED_HOST}"$'\n'"    address: localhost"$'\n'"    user: $(whoami)"$'\n'"    local: true"

    while true; do
        read -rp "Add a remote host? (hostname or IP, blank to finish): " RHOST
        [[ -z "$RHOST" ]] && break
        read -rp "  SSH user for $RHOST [$(whoami)]: " RUSER
        RUSER=${RUSER:-$(whoami)}
        HOSTS_ENTRIES+=$'\n'"  - name: ${RHOST}"$'\n'"    address: ${RHOST}"$'\n'"    user: ${RUSER}"$'\n'"    local: false"
        info "Added $RUSER@$RHOST"
    done

    echo "$HOSTS_ENTRIES" > "$HOSTS_FILE"
    info "hosts.yml written."
fi

# ── Claude Desktop MCP wiring ──────────────────────────────────────────────
section "Claude Desktop Integration (optional)"
echo "This wires the Lynis MCP server into Claude Desktop so you can"
echo "ask Claude to run audits and get remediation guidance in chat."
echo ""

CLAUDE_CONFIG=""
for p in \
    "$HOME/.config/Claude/claude_desktop_config.json" \
    "$HOME/Library/Application Support/Claude/claude_desktop_config.json"; do
    [[ -f "$p" ]] && CLAUDE_CONFIG="$p" && break
done

if [[ -z "$CLAUDE_CONFIG" ]]; then
    warn "Claude Desktop config not found — skipping MCP wiring."
    warn "Run scripts/install-claude-mcp.sh manually after installing Claude Desktop."
else
    read -rp "Wire lynis-mcp into Claude Desktop? [Y/n]: " yn
    if [[ ! "$yn" =~ ^[Nn] ]]; then
        bash "$SCRIPT_DIR/install-claude-mcp.sh" "$CLAUDE_CONFIG"
    fi
fi

# ── Start the stack ────────────────────────────────────────────────────────
section "Starting Stack"
read -rp "Start the telemetry stack now? [Y/n]: " yn
if [[ ! "$yn" =~ ^[Nn] ]]; then
    cd "$BASE_DIR"
    sg docker "docker compose build && docker compose up -d"
    echo ""
    info "Stack is up!"
    echo ""
    echo "  Grafana:  http://localhost:3000"
    echo "  InfluxDB: http://localhost:8086"
    echo ""
    echo "  Run your first audit: telem scan"
fi

echo ""
info "Setup complete. Run 'telem help' to see all commands."
